# Site Settings
lang: ja
title: OS4 ジキルサイト構築
tagline: Hiroshi Inoue
email: 
description: >
  OS4 ジキルでサイトを構築しました（井上浩）
baseurl: ""
url: ""
permalink: pretty
favicon: /0852org_trmg.png
# favicon: /favicon.ico
# gh_sponsor: 
#hide_share_buttons: true
theme_color: '#8b008b'
#fixed_navbar: top
#direction: one of <ltr, rtl, auto>, default: ltr

paginate: 5
paginate_path: "/blog/page:num"

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  # shortname: my_disqus_shortname
  # shortname: 

remote_theme: chrisrhymes/bulma-clean-theme
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-redirect-from

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass

#google_analytics: UA-code-here

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Hiroshi Inoue"
      layout: post
      image: 
      show_sidebar: true

markdown: kramdown
highlighter: rouge

footer_menu: example_footer_menu

collections:
  products: 
    output: true
    layout: product
    image: 
    show_sidebar: false
